/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javadevs;

import java.awt.event.KeyEvent;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author pand1
 */
public class JFrame3 extends javax.swing.JFrame {
    LinkedList<LinkedList<String>> sublist = new LinkedList<LinkedList<String>>();
    static int counter;
    
    /**
     * Creates new form JFrame3
     */
    public JFrame3(int counter) {
        this.counter = counter;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNext = new javax.swing.JButton();
        jOK = new javax.swing.JButton();
        jName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jNext.setText("Next");
        jNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextActionPerformed(evt);
            }
        });
        jNext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNextKeyPressed(evt);
            }
        });

        jOK.setText("OK");
        jOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOKActionPerformed(evt);
            }
        });
        jOK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jOKKeyPressed(evt);
            }
        });

        jLabel1.setText("Give the name of the next field:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jNext, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jOK, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNext)
                    .addComponent(jOK))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextActionPerformed
        // TODO add your handling code here:
        JFrameList list = new JFrameList();
        
        sublist = list.getList();
        String name = jName.getText();
        if (!name.equals(sublist.get(0).get(0))){
            sublist.add(new LinkedList<String>());
            sublist.get(counter).add(name);
            list.setList(sublist);
            counter++;
            JFrame3.this.setVisible(false);
            new JFrame3(counter).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "!! Field name cannot be the same with the primary key field !!\n Please try again", "Error", JOptionPane.ERROR_MESSAGE);
            JFrame3.this.setVisible(false);
            new JFrame3(counter).setVisible(true);
        }
        
       
    }//GEN-LAST:event_jNextActionPerformed

    private void jOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOKActionPerformed
        // TODO add your handling code here:
        JFrameList list = new JFrameList();
        
        sublist = list.getList();
        String name = jName.getText();
        if (!name.equals(sublist.get(0).get(0))){
            sublist.add(new LinkedList<String>());
            sublist.get(counter).add(name);
            list.setList(sublist);
            //JOptionPane.showMessageDialog(null, list.getList());
            JFrame3.this.setVisible(false);
            new JFrameMenu().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "!! Field name cannot be the same with the primary key field !!\n Please try again", "Error", JOptionPane.ERROR_MESSAGE);
            JFrame3.this.setVisible(false);
            new JFrame3(counter).setVisible(true);
        }
        
    }//GEN-LAST:event_jOKActionPerformed

    private void jNextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNextKeyPressed
        // TODO add your handling code here:
         JFrameList list = new JFrameList();
        
        sublist = list.getList();
        String name = jName.getText();
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
              if (!name.equals(sublist.get(0).get(0))){
                sublist.add(new LinkedList<String>());
                sublist.get(counter).add(name);
                counter++;
                JFrame3.this.setVisible(false);
                new JFrame3(counter).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "!! Field name cannot be the same with the primary key field !!\n Please try again", "Error", JOptionPane.ERROR_MESSAGE);
                JFrame3.this.setVisible(false);
                new JFrame3(counter).setVisible(true);
            }
        }
    }//GEN-LAST:event_jNextKeyPressed

    private void jOKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jOKKeyPressed
        // TODO add your handling code here:
        JFrameList list = new JFrameList();
        
        sublist = list.getList();
        String name = jName.getText();
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
           if (!name.equals(sublist.get(0).get(0))){
                sublist.add(new LinkedList<String>());
                sublist.get(counter).add(name);
                list.setList(sublist);
                //JOptionPane.showMessageDialog(null, list.getList());
                JFrame3.this.setVisible(false);
                new JFrameMenu().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "!! Field name cannot be the same with the primary key field !!\n Please try again", "Error", JOptionPane.ERROR_MESSAGE);
                JFrame3.this.setVisible(false);
                new JFrame3(counter).setVisible(true);
            }
        }
    }//GEN-LAST:event_jOKKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame3(counter).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jName;
    private javax.swing.JButton jNext;
    private javax.swing.JButton jOK;
    // End of variables declaration//GEN-END:variables
}
