/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javadevs;

import java.awt.event.KeyEvent;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author pand1
 */
public class JFrame2 extends javax.swing.JFrame {
    LinkedList<LinkedList<String>> sublist = new LinkedList<LinkedList<String>>();
    
    /**
     * Creates new form JFrame2
     */
    public JFrame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jKeyName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jNext = new javax.swing.JButton();
        jOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jKeyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKeyNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Give the name of the primary key field:");

        jNext.setText("Next");
        jNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextActionPerformed(evt);
            }
        });
        jNext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNextKeyPressed(evt);
            }
        });

        jOK.setText("OK");
        jOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOKActionPerformed(evt);
            }
        });
        jOK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jOKKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jKeyName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jNext, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jOK, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jKeyName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNext)
                    .addComponent(jOK))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jKeyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKeyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jKeyNameActionPerformed

    private void jNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextActionPerformed
        // TODO add your handling code here:
        String keyName = jKeyName.getText();
        if (keyName.equals("")){
            JOptionPane.showMessageDialog(null, "!! Primary key cannot be null !!", "Error", JOptionPane.ERROR_MESSAGE);
            JFrame2.this.setVisible(false);
            new JFrame2().setVisible(true);
        } else {
            sublist.add(new LinkedList<String>());
            sublist.getFirst().add(keyName);
            JFrameList list = new JFrameList();
            list.setList(sublist);
            JFrame2.this.setVisible(false);
            new JFrame3(1).setVisible(true);
        }
        //JOptionPane.showMessageDialog(null, sublist);
        
        JFrameList list = new JFrameList();
        list.setList(sublist);
     
        
    }//GEN-LAST:event_jNextActionPerformed

    private void jNextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNextKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            
            String keyName = jKeyName.getText();
            if (keyName.equals("")){
                JOptionPane.showMessageDialog(null, "!! Primary key cannot be null !!   "
                        + "", "Error", JOptionPane.ERROR_MESSAGE);
                JFrame2.this.setVisible(false);
                new JFrame2().setVisible(true);
            } else {
                sublist.add(new LinkedList<String>());
                sublist.getFirst().add(keyName);
                JFrameList list = new JFrameList();
                list.setList(sublist);
                JFrame2.this.setVisible(false);
                new JFrame3(1).setVisible(true);
            }
            //JOptionPane.showMessageDialog(null, sublist);

            
        }
    }//GEN-LAST:event_jNextKeyPressed

    private void jOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOKActionPerformed
        // TODO add your handling code here:
            String keyName = jKeyName.getText();
        if (keyName.equals("")){
            JOptionPane.showMessageDialog(null, "!! Primary key cannot be null !!", "Error", JOptionPane.ERROR_MESSAGE);
            JFrame2.this.setVisible(false);
            new JFrame2().setVisible(true);
        } else {
            sublist.add(new LinkedList<String>());
            sublist.getFirst().add(keyName);
            JFrameList list = new JFrameList();
            list.setList(sublist);
            JFrame2.this.setVisible(false);
            new JFrameMenu().setVisible(true);
        }
        //JOptionPane.showMessageDialog(null, sublist);
        
    
    }//GEN-LAST:event_jOKActionPerformed

    private void jOKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jOKKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            
            String keyName = jKeyName.getText();
            if (keyName.equals("")){
                JOptionPane.showMessageDialog(null, "!! Primary key cannot be null !!   "
                        + "", "Error", JOptionPane.ERROR_MESSAGE);
                JFrame2.this.setVisible(false);
                new JFrame2().setVisible(true);
            } else {
                sublist.add(new LinkedList<String>());
                sublist.getFirst().add(keyName);
                JFrameList list = new JFrameList();
                list.setList(sublist);
                JFrame2.this.setVisible(false);
                new JFrameMenu().setVisible(true);
            }
            //JOptionPane.showMessageDialog(null, sublist);
;
        }
    }//GEN-LAST:event_jOKKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField jKeyName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jNext;
    private javax.swing.JButton jOK;
    // End of variables declaration//GEN-END:variables
}
